name: KumandrasEconomy
version: ${project.version}
main: me.jaymar921.kumandraseconomy.KumandrasEconomy
api-version: 1.16
authors: [ JayMar921 ]
softdepend: [Vault,CustomEnchantments]
website: https://www.spigotmc.org/resources/authors/jaymar921.1073076/

commands:

    kumandra:
        description: Command for Kumandra Economy plugin
        aliases: [kd]
        usage: /kumandra [Sub Commands]
        permission: kumandraseconomy.kumandra
        permission-message: You have no permission to use this command
    ktrade:
        description: Command for Trading [Kumandra Economy Plugin]
        usage: /ktrade [Sub Commands]

permissions:
    kumandraseconomy.kumandra:
        desription: Gives access to all plugin commands
        default: true
        children:
            kumandraseconomy.kumandra.balance: true
            kumandraseconomy.kumandra.pay: true
            kumandraseconomy.kumandra.economy: false
            kumandraseconomy.kumandra.trade: true
            kumandraseconomy.kumandra.deliver: true
            kumandraseconomy.kumandra.job: true
            kumandraseconomy.kumandra.shop: true
            kumandraseconomy.kumandra.shopAdmin: false

    kumandraseconomy.kumandra.balance:
        description: Show the player's account
        default: true

    kumandraseconomy.kumandra.economy:
        description: Add or remove money from player
        default: op

    kumandraseconomy.kumandra.pay:
        description: Pay money to a player's account
        default: true

    kumandraseconomy.kumandra.trade:
        description: Trade with players
        default: true

    kumandraseconomy.kumandra.deliver:
        description: Deliver items to players
        default: true

    kumandraseconomy.kumandra.job:
        description: Join jobs
        default: true

    kumandraseconomy.kumandra.shop:
        description: Create shops
        default: true

    kumandraseconomy.kumandra.shopAdmin:
        description: Create/Modify shops
        default: op